### PR TITLE
Atualiza README

### PR DESCRIPTION
**Pull request by Fuhrmann**
Atualiza os links para o packgist que estavam errados

### CODE REVIEW

**Comment by CentaurWarchief** [comment]
@Fuhrmann :beers:

**Comment by Fuhrmann** [comment]
I don't have access to a terminal right now, so I'll just delete this commit and send another one since I can't edit in GitHub.

**Comment by CentaurWarchief** [comment]
@Fuhrmann 

Aw, so GitHub is the source of your commit, gotcha.

**Comment by Fuhrmann** [comment]
Yes, I was looking for a package like yours and saw your project, so I sent a pull request using GitHub.

**Pull request closed without merging**
